tap "heroku/brew"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "leoafarias/fvm"
brew "anyenv"
brew "aspell"
brew "awscli"
brew "circleci"
brew "cocoapods"
brew "colordiff"
brew "coreutils"
brew "deno"
brew "diffutils"
brew "direnv"
brew "emojify"
brew "eza"
brew "ffmpeg"
brew "findutils"
brew "fzf"
brew "fzy"
brew "gh"
brew "ghq"
brew "gibo"
brew "git"
brew "git-lfs"
brew "git-secrets"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "grep"
brew "gzip"
brew "hub"
brew "imagemagick"
brew "jq"
brew "mas"
brew "minikube"
brew "nkf"
brew "node"
brew "peco"
brew "php"
brew "pinentry-mac"
brew "switchaudio-osx"
brew "telnet"
brew "tig"
brew "tmux"
brew "tree"
brew "vim"
brew "watch"
brew "wget"
brew "yarn"
brew "yq"
brew "zsh"
brew "heroku/brew/heroku"
brew "leoafarias/fvm/fvm"
cask "adobe-creative-cloud"
cask "alacritty"
cask "alfred"
cask "android-studio"
cask "cmd-eikana"
cask "coteditor"
cask "dash"
cask "discord"
cask "docker"
cask "flutter"
cask "font-ricty-diminished"
cask "github-beta"
cask "google-chrome-beta"
cask "google-drive"
cask "google-japanese-ime-dev"
cask "istat-menus"
cask "jetbrains-toolbox"
cask "logitech-options"
cask "notion"
cask "onyx"
cask "proxyman"
cask "sequel-ace"
cask "sketch-beta"
cask "slack-beta"
cask "visual-studio-code-insiders"
cask "vmware-horizon-client"
cask "webex"
cask "witch"
cask "zoom"
mas "com.adriangranados.wifiexplorerlite", id: 1408727408
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "MindNode", id: 1289197285
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Skitch", id: 425955336
mas "Solves", id: 1394359548
mas "The Unarchiver", id: 425424353
mas "WinArchiver Lite", id: 414855915
mas "Xcode", id: 497799835
